openapi: 3.0.0
info:
  title: api-gateway
  description: simple openapi gateway for gcp
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /v1/intro/:text:
    get:
      summary: Return greetings
      operationId: intro-text
      
